### PR TITLE
#59 backend upvoting downvoting

### PR DESCRIPTION
**Pull request by sajanjohal**

### CODE REVIEW

**Review by sleepyStick — APPROVED** [review]
lgtm!

**Review by wes-curl — APPROVED** [review]
I'm glad to see the removal of get all reviews. Get professor made that redundant.

**Review by aeller-design — APPROVED** [review]
looks good to me!

**Comment by ashahrod** [comment]
looks good!

**Comment by sajanjohal** [comment]
> lgtm!
> looks good to me!
> looks good!

Thanks guys!

> I'm glad to see the removal of get all reviews. Get professor made that redundant.

Yeah me too!

**Pull request merged**
