### PR TITLE
wrote tests for course services

### PR DESCRIPTION
**Pull request by sleepyStick**

### CODE REVIEW

**Review by aeller-design — APPROVED** [review]
New tests look great!

**Review by wes-curl — APPROVED** [review]
Looks good from where I stand.

**Comment by ashahrod** [comment]
Looks good to me!

**Review by sajanjohal — CHANGES_REQUESTED** [review]
Looks good for the most part. plz run prettier before merging :)

**Review by ashahrod — COMMENTED** [review]
Looks good to me! Good tests

**Review by ashahrod — APPROVED** [review]

**Comment by sleepyStick** [comment]
> Looks good for the most part. plz run prettier before merging :)

sorry! I thought I did! >.<

**Pull request merged**
