### PR TITLE
Unify frontend Incorporation

### PR DESCRIPTION
**Pull request by wes-curl**
Changes include:
-CSS for all three pages
-JS for some page elements
-API connection for course/:course
-HTML finished.

### CODE REVIEW

**Review by aeller-design — COMMENTED** [review]
for some reason it is only showing me the files that you deleted and not the other changes noted.

**Comment by wes-curl** [comment]
Yeah. That's because I accidently included the changes listed in the previous pull request. The files that have actually changed are (in the frontend) App.js, all the css files (though you really don't need to review those),  submitRating.js, and professorListElement.js. The rest of the changes are HTML, not really worth review.

**Comment by ashahrod** [comment]
Looks good to me!

**Comment by sleepyStick** [comment]
looks good to me 👍

**Pull request merged**
